induction c with d hd generalizing b,
intro abao,
rw mul_zero at abao,
have hv := eq_zero_or_eq_zero_of_mul_eq_zero a b abao,
cases hv with a b,
exfalso,
apply ha,
exact a,
exact b,
intro abasd,
cases b,
rw mul_zero at abasd,
symmetry at abasd,
rw mul_eq_zero_iff at abasd,
cases abasd,
have hc := ha abasd,
exfalso,
exact  hc,
symmetry,
exact abasd,
repeat {rw mul_succ at abasd},
rw add_right_cancel_iff at abasd,
repeat {rw succ_eq_add_one},
rw add_right_cancel_iff,
apply hd,
exact abasd,